add traverseResult and sequenceResult for kotlin.Sequence
arrow-kt/arrow pull request #2601
Opened 2021-12-19 17:32 UTC by abendt

https://github.com/arrow-kt/arrow/issues/2535

this adds _sequenceResult_ and _traverseResult_ for _kotlin.Sequence_

2021-12-19 20:29 UTC, nomisRev approved these changes
Thanks @abendt 👍

2021-12-20 09:45 UTC, nomisRev commented on arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Sequence.kt
> +public fun <A, B> Sequence<A>.traverseResult(f: (A) -> Result<B>): Result<Sequence<B>> {
```suggestion
public inline fun <A, B> Sequence<A>.traverseResult(f: (A) -> Result<B>): Result<Sequence<B>> {
```

2021-12-20 09:45 UTC, nomisRev requested changes
Actually, sorry @abendt. That function should be `inline` to allow for the suspension to go through.

2021-12-20 14:01 UTC, abendt commented
Another question @nomisRev. i also wanted to have a look at the _traverseX/sequenceX_ operators for Flows.
Is this a correct signature for e.g. the Result variant?

`public suspend fun <A, B> Flow<A>.traverseResult(f: suspend (A) -> Result<B>): Result<Flow<B>>`

2021-12-20 14:38 UTC, nomisRev commented
Well the `Sequence` signature is actually already a bit missleading since it's actually processing **all** the values of the `Sequence`/`Flow` before returning. So it's actually not a sequencing/streaming operator, but a terminal operator.

```
public suspend fun <A, B> Sequence<A>.traverseResult(f: suspend (A) -> Result<B>): Result<List<B>>
public suspend fun <A, B> Flow<A>.traverseResult(f: suspend (A) -> Result<B>): Result<List<B>>
```

2021-12-20 14:49 UTC, abendt commented
> Well the `Sequence` signature is actually already a bit missleading since it's actually processing **all** the values of the `Sequence`/`Flow` before returning. So it's actually not a sequencing/streaming operator, but a terminal operator.

true, that makes sense. Should i change the signature of the `Sequence.traverseResult` then too? Downside i see: there are the existing _traverseOption/Validated/..._  functions. These should ideally be changed too for consistency. Ofc this would be a breaking API change.

wdyt?

2021-12-24 10:10 UTC, nomisRev requested changes
Hey @abendt,

> rue, that makes sense. Should i change the signature of the Sequence.traverseResult then too?
> Ofc this would be a breaking API change.

I've been thinking about it, and I think we should actually deprecate the current `traverse` functions on `Sequence` since they're missleading. They're the equivalent of `sequence.toList().traverseXXX`.

So these functions actually promote an anti-pattern, so I would actually be in favor of deprecating them all together instead of updating them since an alias for `toList().traverse` seems redundant.

Since 1.0.0 we have to be very careful as to what functionality/methods we add since we can not easily remove/change the API. Having bloated, very large APIs surface is a downside not rather than an upside.

What do you think?

2021-12-24 10:11 UTC, nomisRev commented
I looked into if we can make a sequence safe traverse function but since `SequenceScope` is designed as an `abstract class` with an `internal constructor` we cannot mix the effect as we could do if `SequenceScope` was an interface.
Otherwise we could create `interface EitherSequence<E, A> : EitherEffect<E>, SequenceScope<A>`.

2021-12-24 12:10 UTC, raulraja commented
Thanks, @abendt. I propose we put this on hold, including adding additional functions to Arrow until the maintainers regroup in January. There is a plan to meet to discuss the Arrow Roadmap for 2022, including a review of needed methods and others that will get deprecated before 2.0.

2022-03-04 12:40 UTC, closed without merging