Implement sealed class Lenses
arrow-kt/arrow pull request #3359
Opened 2024-01-24 13:54 UTC by maksym-moroz

Addresses #2829 
Implements Lenses for sealed class properties when the properties are abstract & without extension receiver andsubclasses are data classes that override properties in the constructor. 
If that's not the case emit a info log message explaining why Lens is not being generated.
Additional cleanup to target logic.

2024-01-25 11:58 UTC, serras commented
@maksym-moroz can you run the `spotlessApply` task and re-commit?

2024-01-26 13:56 UTC, maksym-moroz commented
@serras I did just that and it didn't show any issues with build

2024-01-28 08:04 UTC, serras commented
The automatic Spotless commit was not working, I've done it manually. This should (hopefully) turn the build green.

2024-01-30 10:05 UTC, serras requested changes
Thanks for this great work. Not only implementing the feature, but also cleaning the code a bit on the go :)

I've left a few comments about things (mostly tests) that I think should be in the code before merging it in `main`.

2024-01-30 10:05 UTC, serras commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-all.zip
What is the reasoning for this change?

2024-01-30 10:05 UTC, serras commented on arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt
> +  fun `Lens for sealed class property`() {
I am missing three other cases for test:
1. More than one class extending the sealed one,
2. Data classes defined outside of the sealed class,
3. Sealed class with zero inheritors.

2024-02-08 10:24 UTC, merged